import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Map from '../components/Map'
import dynamic from "next/dynamic"

const MyMap = dynamic(() => import("../components/Map"), { ssr: false })

const Home: NextPage = () => {
  const position = [51.505, -0.09]
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav class="bg-white p-2 mt-0 fixed w-full z-10 top-0">
        <div class="container mx-auto flex flex-wrap items-center">
          <div class="flex-col w-full md:w-1/2 justify-center md:justify-start text-white ">
            <h1 class="text-black text-2xl pl-2 font-extrabold"><i class="em em-grinning"></i> React + Leaflet Playground</h1>
            <p className="text-sky-500 hover:text-sky-600 pl-2">
              crafted by aji
            </p>
          </div>
        </div>
      </nav>

      <div className="flex items-center justify-center h-screen">
        <div className="container mt-20 p-10 h-2/3">
          <MyMap />
        </div>
      </div>

    </div>
  )
}

export default Home